name: Build and Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the specific branch
        uses: actions/checkout@v4
        with:
          ref: feature-UserLoginBooking-Sumathi

      - name: Install Dependencies
        run: |
          cd feature-UserLoginBooking-Sumathi
          npm install

      - name: Build Project
        run: |
          cd feature-UserLoginBooking-Sumathi
          npm run build --if-present

      - name: Run Tests
        run: |
          cd feature-UserLoginBooking-Sumathi
          npm test
